version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    schedule:
      interval: monthly
      time: '08:00'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']

  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
      time: '08:00'
