name: ESLint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Prepare .npmrc file
        run: |
          echo "@grupoboticario:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
          cat ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHA_PACKAGES }}

      - name: Install modules
        run: yarn install

      - name: Run ESLint
        run: yarn run lint
